apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: loki-app-set
spec:
  generators:
  - list:
      elements:
      - cluster: stage
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'grafana-loki'
    spec:
      syncPolicy:
        automated:
          selfHeal: true
          prune : true
      project: default
      source:
        repoURL: https://github.com/farooq89/loki.git
        targetRevision: HEAD
        path: ./
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: grafana-loki